# $OpenBSD$

COMMENT =               "automated password generator" clone written in Go

GH_ACCOUNT =            wneessen
GH_PROJECT =            apg-go
GH_TAGNAME =            v0.3.1

CATEGORIES =            security

MAINTAINER =            Winni Neessen <wn@neessen.net>

# MIT
PERMIT_PACKAGE =        Yes

MODULES =               lang/go
MODGO_TYPE =            bin

ALL_TARGET =            wneessen/apg-go

.include <bsd.port.mk>