# SPDX-FileCopyrightText: 2022 Winni Neessen <winni@neessen.dev>
#
# SPDX-License-Identifier: CC0-1.0

name: REUSE Compliance Check
permissions:
  contents: read

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@28cf8f33bc50f4c306f52e38fe3826717dea63dc # v1.3.0
